__BASE__: [
  '../coco.yaml',
  './hyp.scratch.high.yaml',
  './yolov8-base.yaml'
]

network:
  depth_multiple: 1.00  # scales module repeats
  width_multiple: 1.00  # scales convolution channels
  max_channels: 512
